### ISSUE TITLE
UDT中脚本卡在基于cv的find函数

### ISSUE THREAD

**Issue by Yezhj1** [assistd/scrcpy#4]
## 问题描述
在UDT中跑自动化测试脚本，整个进程执行查找图片find函数时卡住，造成进程卡住。
- 环境：uitrace 2.1.2
- scrcpy-server的md5为8dbea94ed353c005a9664467723d9dfe

<img width="1025" alt="企业微信截图_ede98816-02a2-48d3-952e-a9fbaf4510d0" src="https://user-images.githubusercontent.com/102509923/196332918-7bcf2f72-17c5-4ea0-a3d9-22765d4cef96.png">
<img width="1864" alt="企业微信截图_2b078ab5-9661-4563-b642-9c4220aef1d2" src="https://user-images.githubusercontent.com/102509923/196332932-38909738-eb91-42c4-872b-78f334b3821f.png">

**Comment by HEZI0427** [comment]
分析：
收到转屏通知消息，未处理导致后续图片长度读取错位， 触发循环
<img width="1348" alt="企业微信截图_21f62c19-ec50-41ca-8a64-63b490c3ba7c" src="https://user-images.githubusercontent.com/7960376/196446604-9becad96-0745-4bfd-94e4-5384d773fa80.png">

处理方式：
默认关闭转屏主动推送
